name: Build Android APK
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Extract File
      run: tar -xf BoardBoss10.tar.gz
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
      with:
        gradle-version: '8.7'
    - name: Build APK
      run: |
        cd $(dirname $(find . -name "settings.gradle" | head -1))
        mkdir -p app
        cp ${GITHUB_WORKSPACE}/google-services.json app/
        sed -i 's/FAIL_ON_PROJECT_REPOS/PREFER_PROJECT/g' settings.gradle
        find . -name "AndroidManifest.xml" -exec sed -i 's/@mipmap\/ic_launcher_round/@android:drawable\/sym_def_app_icon/g' {} +
        find . -name "AndroidManifest.xml" -exec sed -i 's/@mipmap\/ic_launcher/@android:drawable\/sym_def_app_icon/g' {} +
        find . -type f -name "*.xml" -exec sed -i 's/@android:drawable\/ic_menu_home/@android:drawable\/ic_menu_gallery/g' {} +
        gradle assembleDebug
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: My-App-APK
        path: '**/*.apk'
        
