name: Build Android APK
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Extract File
      run: tar -xf BoardBoss10.tar.gz
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Build APK
      run: |
        cd $(dirname $(find . -name "build.gradle" | head -1))
        sed -i 's/FAIL_ON_PROJECT_REPOS/PREFER_PROJECT/g' settings.gradle
        gradle assembleDebug
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: My-App-APK
        path: '**/*.apk'
